# Set the base image to Ubuntu
FROM    ubuntu:14.04

# File Author / Maintainer
MAINTAINER Van Thanh "vanthanh@.co"

# Install Node.js and other dependencies
RUN apt-get update && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup | sudo bash - && \
    apt-get -y install python build-essential nodejs git && \
    apt-get install -y vim

# Install nodemon
RUN npm install -g nodemon

#RUN  echo "    IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config
RUN mkdir /root/.ssh
ADD id_rsa /root/.ssh/id_rsa
ADD id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 700 /root/.ssh
RUN ssh-keyscan -t rsa git.applications.com > /root/.ssh/known_hosts
#RUN chown -R ubuntu:ubuntu /home/ubuntu/.ssh
# Provides cached layer for node_modules
#ADD package.json /tmp/package.json
#RUN cd /tmp && npm install
RUN mkdir /root/web && cd /root/web && mkdir TRAPI
RUN cd /root/web/TRAPI && git clone git@git.applications.com:-staffs/TRAPI.git && cd TRAPI && git checkout timestamp_api && git pull origin timestamp_api && cd timestamp_api && npm install

RUN cd /root/web/TRAPI/TRAPI/timestamp_api && chmod -R 777 logs
RUN sed -i -e 's/127.0.0.1/172.17.42.1/g' /root/web/TRAPI/TRAPI/timestamp_api/config/config.js
RUN sed -i -e 's/localhost/172.17.42.1/g' /root/web/TRAPI/TRAPI/timestamp_api/config/config.js
#RUN sed -i -e 's/127.0.0.1/172.17.42.1/g' /root/web/TRAPI/TRAPI/timestamp_api/config/express.js
RUN cd /root/web/TRAPI/TRAPI/timestamp_api && echo "cd /root/web/TRAPI/TRAPI/timestamp_api && node app.js" > run.sh && chmod +x run.sh
#RUN mkdir /r^Coot/web/TRWeb/TRWeb/admin/logs
# Define working directory
WORKDIR /root
#ADD . /home/ubuntu

# Expose port
EXPOSE  4001
#RUN service redis-server start

#ENTRYPOINT  ["/root/web/TRWeb/TRWeb/admin/run.sh"]
## Run app using nodemon
CMD ["sh", "/root/web/TRAPI/TRAPI/timestamp_api/run.sh"]
#RUN service redis-server start
# Run app using nodemon
#CMD ["node", "/root/web/TRWeb/TRWeb/admin/app.js"]
