# Set the base image to Ubuntu
FROM    ubuntu:14.04

# File Author / Maintainer
MAINTAINER Van Thanh "thanh.nguyen2891@gmail.com"

# Install Node.js and other dependencies
RUN apt-get update && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup | sudo bash - && \
    apt-get -y install python build-essential nodejs git

# Install nodemon
RUN npm install -g nodemon

#RUN  echo "    IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config
RUN mkdir /root/.ssh
ADD id_rsa /root/.ssh/id_rsa
ADD id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 700 /root/.ssh
RUN ssh-keyscan -t rsa git.applications.com > /root/.ssh/known_hosts
#RUN chown -R ubuntu:ubuntu /home/ubuntu/.ssh
# Provides cached layer for node_modules
#ADD package.json /tmp/package.json
#RUN cd /tmp && npm install
RUN mkdir /root/web && cd /root/web && mkdir web4008Web
RUN cd /root/web/web4008Web && git clone git@git.applications.com:-staffs/web4008Web.git && cd web4008Web && git checkout feature/web && git pull origin feature/web && cd source && npm install
RUN cd /root/web/web4008Web/web4008Web/source && mkdir logs && chmod -R 777 logs
RUN mv /root/web/web4008Web/web4008Web/source/configs/config_web4008.js /root/web/web4008Web/web4008Web/source/configs/config.js
RUN sed -i -e 's/127.0.0.1/172.17.42.1/g' /root/web/web4008Web/web4008Web/source/configs/config.js
RUN sed -i -e 's/localhost/172.17.42.1/g' /root/web/web4008Web/web4008Web/source/configs/config.js
RUN sed -i -e 's/127.0.0.1/172.17.42.1/g' /root/web/web4008Web/web4008Web/source/configs/express.js
RUN cd /root/web/web4008Web/web4008Web/source && echo "cd /root/web/web4008Web/web4008Web/source && node app.js" > run.sh && chmod +x run.sh
#RUN mkdir /r^Coot/web/web4008Web/web4008Web/admin/logs
# Define working directory
WORKDIR /root
#ADD . /home/ubuntu

# Expose port
EXPOSE  4008
#RUN service redis-server start

#ENTRYPOINT  ["/root/web/web4008Web/web4008Web/admin/run.sh"]
## Run app using nodemon
CMD ["sh", "/root/web/web4008Web/web4008Web/source/run.sh"]

#RUN mkdir /r^Coot/web/web4008Web/web4008Web/admin/logs
# Define working directory
